steps:
- task: UseNode@1
  displayName: 'Use Node 18.x'
  inputs:
    version : 18.x

 - task: PowerShell@2
  inputs:
    targetType: "inline"
    script: |
      $ErrorActionPreference = 'Stop'
      $ProgressPreference = 'SilentlyContinue'
  displayName: "Add PS Perms"

- task: PowerShell@2
  inputs:
    targetType: "inline"
    script: |
      .\Add-Font.ps1 -path .\Fonts\
    workingDirectory: '$(Build.SourcesDirectory)\.pipelines\templates'
    displayName: "Install Chrome Fonts"

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run compile