steps:
- task: UseNode@1
  displayName: 'Use Node 18.x'
  inputs:
    version : 18.x

- task: PowerShell@2
  inputs:
    targetType: "inline"
    script: |
      # URL of the font file
      $fontUrl = "https://fonts.gstatic.com/s/roboto/v27/KFOlCnqEu92Fr1MmEU9fBBc9.ttf"
      
      # Destination folder for installing the font
      $destinationFolder = "$(Build.SourcesDirectory)\.pipelines\templates\Fonts"
      
      # Download the font file
      $fontPath = Join-Path $destinationFolder "font.ttf"
      Invoke-WebRequest -Uri $fontUrl -OutFile $fontPath
      
      # Install the font
      $fontRegistryPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"
      $fontName = (Get-Item $fontPath).BaseName
      $fontRegistryEntry = @{
          Path = $fontPath
          Destination = $destinationFolder
          Name = $fontName
      }
      $null = New-Item -Path $fontRegistryPath -Force
      $null = New-ItemProperty -Path $fontRegistryPath -Name $fontName -Value $fontRegistryEntry -PropertyType ExpandString -Force
    workingDirectory: '$(Build.SourcesDirectory)\.pipelines\templates'
  displayName: "Install Chrome Fonts"

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: custom
    customCommand: run compile