name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup BuildNumber
      run: |
        echo "##[set-output name=BuildNumber;]$(Build.SourceBranchName)_$(Build.SourceVersion)"
      id: setBuildNumber

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Use Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Build
      run: npm run compile

    - name: Pre-test
      run: npm run pretest

    - name: Test
      run: npm test

  package:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup BuildNumber
      run: |
        echo "##[set-output name=BuildNumber;]$(Build.SourceBranchName)_$(Build.SourceVersion)"
      id: setBuildNumber

    - name: Install
      run: npm ci

    - name: Package
      run: npm run package
    
    - name: Create Package
      run: npm run create-package

    - name: Copy vsix to output directory
      run: |
        mkdir -p ${{ github.workspace }}/out
        cp -R ${{ github.workspace }}/**/*.vsix ${{ github.workspace }}/out
    